services:
  api:
    build: .
    container_name: lov-portal-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    environment:
      BIGQUERY_PROJECT: sandbox-lov
      BIGQUERY_DATASET: lov_gold
      BIGQUERY_LOCATION: asia-southeast2
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sandbox-lov-760ab321486a.json
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./secrets/sandbox-lov-760ab321486a.json:/secrets/sandbox-lov-760ab321486a.json:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: lov-portal-redis
    ports:
      - "6379:6379"